# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true

knife4j:
  enable: true
  basic:
    enable: false
    username: admin
    password: admin
  setting:
    enableFooter: false

spring:
  #  # 环境 dev|test|prod
  #  profiles:
  #    active: dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
    #MySQL配置
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/course_assistant?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: root
      password: 759260
  messages:
    encoding: UTF-8
    basename: i18n/messages
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zrn.assistant.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型
      logic-delete-field: deleted #默认deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
